language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: nerd1-github
    token:
      secure: "Mr5alG7O1TKnOL0mFqNHQAkmbGbV3FzlNUMMifDNnL13KFZpjvgeWnx+x7qHlwtE74o/J+eNj4yUorB+A0NLHDJKfYci6oiZSQjNDziP/U2d+pIOf8wkynk7iRXHjZxcvwsJDKkEMhT/eTHiXFOxU4+QrZ1X/h9CUGP0pak/gIQ1G5+giKNM/M9+P2Q73RyqQxJfPRnhx/1CBxilZR3ESBXaLFnLlRBnqm72IKthb9ua6B6+Hcsr3BZXVi2TWdC9U29PxXEzrL6CafKRN7KvTrcDfs0AtxT5X048FEpHwZD2kBogoq2U2RgH3VZIuDYyvc1vKHknn8FnzJiN08sDwvz4ZJyo9vmD9pWc/pseEzAKmPxJhbt84BlSIezn6pqNEccdK+cEEwe7czFkyANkj+rGpLrYHY7+CHCiwi9Kd1fejPMq3w5Q/0/+R3bWfO0k1wjqcqzDAu/jecT/AZ6WLylfkh+11NcRg7k3PEgVaC2s2kWy7zvb6iXUzNvWc9SZS1ls1qyamaikhsNxw0JYYZzJ+yzwIjEpJ8O1PLC3Ad0VH/vJ5roKkC8X3Nxz5KQrWgvxUsCwpkcV9qFW2UHywDMTMhyYH+qv/kDQTGNQSnSliWttgf62D/n+zef9LWKZ/gdxM3iKgzr8fuAZFO6pcAzleHJyFvLm7d8iPN+Lsq4="
    branches:
    - master
    - projektsetup
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
notifications:
  email:
    on_success: never
    on_failure: never
