language: java
jdk:
- oraclejdk8
services:
- docker
addons:
  sonarcloud:
    organization: reto7-github
    token: ${SONAR_TOKEN}
    branches:
    - master
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- docker-compose up -d
- docker ps
- python integrationtests.py
- docker-compose down
- docker ps
notifications:
  email:
    on_success: never
    on_failure: never
