language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: nerd1-github
    token:
      secure: b2+qBzT9sY3d+Q3nh6sbdlWufl6qsYFw1jI6/xx+PPjlhNRgeoi9hcN3l3Eyuzz99u26PchJtRkp38F6GpSMRv6odpYKHrgHkVi+oELB0ptM0a7x6RYsw2sObX6KtCDYQRRnWuyM+qgzjNgmzJqjXMWG9PlLlzRHdlauT9PoJBAT1aXATYMCQTrWHbNHM2Sadp7RDG6F8AQlbcpRPcC2HSyy/cEX8HoJIqQb0nIUA4mcXZNe5p3Q2sxkUMZJWKYXpp/E4Q33Z1mqewNKDv57ZeRJR7XPza4EFOv19ig4UpXsDgG56DF765anbqgzMdIyehbwwcR95uPNtyANhjVSUxU4+/RlwkuHuG6v7DYV5mac+xtFRyt9NXOKT40ESET+RN4JYYd3mewEwxGOxIHIS6KihUgnQIuNOkkKc+k63b2/jrQkNVYbbkdQQQEs+ML46TFL30phly0vETK0vhWgfCkbJXd6UljGnxT8vVU+Zm1MXUbEmc8uVkEynmMhiX6PlJC3EV743GPieDjfbBDmWgoJGDMZYZgkJv6y8LlCx5O77NmGjN8yKGA7POy52MOMaOaFYFuKxDsJ2lDJAFkQrNXzF4VRpf7xLXWeU2gF1TGyY2FSi3ITv7gMnjbdFrvvha2DXQHpCBoDKr4xyrrjjMn2HIYgl29SE9Od3g2UnbA=
    branches:
    - master
    - projektsetup
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
notifications:
  email:
    on_success: never
    on_failure: never
dd:
  secure: b2+qBzT9sY3d+Q3nh6sbdlWufl6qsYFw1jI6/xx+PPjlhNRgeoi9hcN3l3Eyuzz99u26PchJtRkp38F6GpSMRv6odpYKHrgHkVi+oELB0ptM0a7x6RYsw2sObX6KtCDYQRRnWuyM+qgzjNgmzJqjXMWG9PlLlzRHdlauT9PoJBAT1aXATYMCQTrWHbNHM2Sadp7RDG6F8AQlbcpRPcC2HSyy/cEX8HoJIqQb0nIUA4mcXZNe5p3Q2sxkUMZJWKYXpp/E4Q33Z1mqewNKDv57ZeRJR7XPza4EFOv19ig4UpXsDgG56DF765anbqgzMdIyehbwwcR95uPNtyANhjVSUxU4+/RlwkuHuG6v7DYV5mac+xtFRyt9NXOKT40ESET+RN4JYYd3mewEwxGOxIHIS6KihUgnQIuNOkkKc+k63b2/jrQkNVYbbkdQQQEs+ML46TFL30phly0vETK0vhWgfCkbJXd6UljGnxT8vVU+Zm1MXUbEmc8uVkEynmMhiX6PlJC3EV743GPieDjfbBDmWgoJGDMZYZgkJv6y8LlCx5O77NmGjN8yKGA7POy52MOMaOaFYFuKxDsJ2lDJAFkQrNXzF4VRpf7xLXWeU2gF1TGyY2FSi3ITv7gMnjbdFrvvha2DXQHpCBoDKr4xyrrjjMn2HIYgl29SE9Od3g2UnbA=
