language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: "nerd1-github"
    token:
      secure: "P7YFRkmyENBF3VTPOzAaKr+2+HUYXxLfd/xZyLfSSllbqWKvVfupWoNlv2U5TgeD7xvKy/JOPWJqS84t59xCbglobf9CFO7Y81hiwDlTQ3iRypMoMVRIHBo/dFWf91mK0GRTxdl2J32o+L8JX56QGEiPkjq8Td7KPDYuZw3tjSzFzvJGDdHpMfqREh+/qb1cB6fpYV1p6bkRDvhqVa+Zw8SYUzMl9aCJwWRGO9n6iD8X//FdBIh4D9crZNh55ddOYiob9nAsyirTKozHn2NPlmkBaY49o6ORZL8AfrTjKIDxNa7eIOvrG01nTqbNXYt7HGCoeRKA8ma3jNoJqaOWNIDyWUt4C/X5W5vHPcYRen2g1p+RnOpicZqiv6e7UULqVuIxDRYEB78HHczxlM8pUmZInLJYjaJJocpEMCRJyQlLhLUyrZM2FYa0jeFgnTH15PZqM6P4VdIxclHJ40TSzKI+cQDIScBSQX5TCCh4csGKeO9mVO6WkDvCxgF2Qgor2S0gj/8zI25T+I46/t+Vs1DogLdvkNg/Om8xlnIQknOA4HUrNidsX2fiYldjmVE3wpMpha6vSvrvNXJC90hqQ6JyNbzP/jT4NtF7bobnmJAg89rfzuusyBo++F1KHyKtP18R+xvg6snCt/lhbwwAj2cY3z2I+svlfnMZVyqVJx8="
    branches:
    - master
    - projektsetup
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
notifications:
  email:
    on_success: never
    on_failure: never
