language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "reto7-github"
    token: ${SONAR_TOKEN}
script:
  #- mvn test
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
notifications:
  email:
    on_success: never
    on_failure: never
