language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: nerd1-github
    token:
      secure: "rpdQw6pYENrkrfeHDAed2TvvAIto6TGEXXHvE/G061r9K7CcsLKDcpXITBNCDhriD1IBrZQpMjjROWrZUdd1Vy+tQYt98Hu0qepXX2+RmfGH7seQySp0ZDuPUxOh9KvvtCpVh0abKcmnmpYrh/o9ip3MV+7dBDnnJQTSMOQgWXpJ2Hj/IZNYeqDnJWlvW1rg0yhA+hoLG2nXpfo4enw6YDyyAWMQ6fUmqE1jysnNbezxqLmFGUQ7odffWbaMSSJ+VG9EHzgaM2VlfgEwc8So+DJESvp8T+TvaAv+EltiXzqUSfwRyi0FIsco1WrKSXZu3fVOXWfJk9f8byfmFe/3x/DMaphQH75qpEJyKMH4GNojDUqKhTgRBKs6Wm1HjstGW+FubpJu0UmEYqxouDMbrqSKis7cD8BHqmQ0LwaV1GiXylgYasHJRwJ064cYlr6JchPpp2VM4I+TA/3FMDDOiScSNLPYyG/UUb1VDyRQ8kKbkSDngSTiLVrvQrVQS6RNoT06Lv9vMBwWHn/34mT2jWATDCYBFFRdvxC4f2OrzNLXDzmWpsZuSMlVxLfr9iNo2g5/7p3nhY40xelLn0wuYV5EEDwH/ZmH2xLyLYBUXl1YxtRop+E7wIvhedJq70qmd9mE8TFGWGT25DuGwHeq1/EsoYnL5fS6uyFMdDDYOTM="
    branches:
    - master
    - projektsetup
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
notifications:
  email:
    on_success: never
    on_failure: never
