language: java
jdk:
- oraclejdk8
services:
- docker
addons:
  sonarcloud:
    organization: reto7-github
    token: ${SONAR_TOKEN}
    branches:
    - master
script:
- travis_retry mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- docker-compose up -d
- docker ps
- bash travis-end-to-end-tests.sh
- docker-compose down
- docker ps
notifications:
  email:
    on_success: never
    on_failure: never
#deploy:
#  skip_cleanup: true
#  provider: heroku
#  api_key:
#      secure: "c72b3fc3-3640-4da9-a28d-4bcb2e0a0d15"
#  on:
#      all_branches: true
