version: '2'
services:
  web:
    image: tomcat
    ports:
      - "8080:8080"
    container_name: stockcomparison_api_container
    volumes:
      - ./target/stock-comparison-1.0.war:/usr/local/tomcat/webapps/ROOT.war
      - ./target/stock-comparison-1.0:/usr/local/tomcat/webapps/ROOT